apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - pedersen.io
      - www.pedersen.io
      - jenkins.pedersen.io
      - derek.pedersen.io
      secretName: pedersen-io-tls
    - hosts:
      - celebrityskateboards.com
      - www.celebrityskateboards.com
      secretName: celebrityskateboards-tls
  rules:
  - host: pedersen.io
    http:
      paths:
      - backend:
          service:
            name: pedersen-spa
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  - host: www.pedersen.io
    http:
      paths:
      - backend:
          service:
            name: pedersen-spa
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  - host: jenkins.pedersen.io
    http:
      paths:
      - backend:
          service:
            name: jenkins-1619548353
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  - host: derek.pedersen.io
    http:
      paths:
      - backend:
          service:
            name: dp-spa-angular
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: resume-api-dotnetcore
            port:
              number: 80
        path: /api
        pathType: ImplementationSpecific
  - host: celebrityskateboards.com
    http:
      paths:
      - backend:
          service:
            name: skatepark-api
            port:
              number: 8080
        path: /api/skateparks
        pathType: ImplementationSpecific
      - backend:
          service:
            name: skatepark-api
            port:
              number: 3000
        path: /api/skateparks/swagger
        pathType: ImplementationSpecific
      - backend:
          service:
            name: celebrityskateboards
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  - host: www.celebrityskateboards.com
    http:
      paths:
      - backend:
          service:
            name: skatepark-api
            port:
              number: 8080
        path: /api/skateparks
        pathType: ImplementationSpecific
      - backend:
          service:
            name: celebrityskateboards
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
